# configs/config.yaml

N_VEHICLES: 30
SCENE_DURATION: 30  # seconds
SLOWDOWN_PERCENTAGE: 10
EGO_AUTOPILOT: False
FOLLOW_POINT_DIST: 8  # meters
REQ_TIME: 1  # seconds
FREQUENCY: 0.1  # simulation tick time
RENDER_CAMERA: True
USE_CUSTOM_MAP: False
NUM_ACTIONS: 3
N_ACTION_PER_MANEUVER: 5
SHOW_ROUTE: True
TRAIN: False
TEST: True
LOAD_MODEL: True
SAVED_MODEL_PATH: "saved_rl_models/1.1/model_55000.zip"
display_width: 1080
display_height: 720
