# The class to instantiate.
_target_: src.envs.carla_env.CarlaGymEnv

# The environment's parameters
render_camera: False
scene_duration: 30  # seconds
slowdown_percentage: 10
ego_autopilot: False
frequency: 0.1  # simulation tick time
use_custom_map: False
show_route: True
preprocess_observation: True
display_width: 1080
display_height: 720
num_actions: 3
n_vehicles: 1
mai_action_space: True
n_actions_per_maneuver: 5

reward_terms:
  TimePenalty:
    weight: 1.0
  GoalImprovementReward:
    weight: 1.0
  GoalReachedReward:
    weight: 50.0
  CollisionPenalty:
    weight: 25.0
  IllegalLaneInvasions:
    weight: 25.0
  RedLightViolation:
    weight: 1.0
  EgoIsTooFast:
    weight: 1.0
  TooSlowPenalty:
    weight: 1.0
  DrivingOnSidewalks:
    weight: 25.0
