# The class to instantiate.
_target_: src.envs.carla_env.CarlaGymEnv

# The environment's parameters
render_camera: False  # If True, the camera sensor is spawned and its output rendered via Pygame.
scene_duration: 30  # the duration of an episode in seconds.
slowdown_percentage: 10  # the percentage of the speed limit by which the vehicles are slowed down.
ego_autopilot: False  # whether to set the autopilot of the ego vehicle.
frequency: 0.1  # simulation tick time
use_custom_map: False  # whether to use a custom OpenDrive map or not.
show_route: True  # whether to display the global route.
preprocess_observation: True  # whether to preprocess the observation.
display_width: 1080  # the width of the screen, if render camera is enabled.
display_height: 720  # the height of the screen, if render camera is enabled.
num_actions: 3  # the number of maneuvers if mai_action_space is False, and the number of actions otherwise.
n_vehicles: 1  # number of vehicles in the simulation (other than the ego vehicle).
mai_action_space: True  # whether to use the Motor.AI action space or not.
n_actions_per_maneuver: 5  # the number of actions per maneuver.
