defaults:
  - env: carla
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Training parameters.
save_path: "./saved_rl_models/"
max_n_steps: 500000

# Evaluation parameters.
eval_frequency: 1000
n_eval_episode: 5

# Tensorboard parameters.
tensorboard_dir: "./tensorboard/"
logging_freq: 1000

# Verbosity.
verbose: 1

hydra:
  output_subdir: null
  run:
    dir: .